# -*- coding: utf-8 -*-
"""13UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103xHJozKvWCa3Pk2oo5fCagZ4W3Icc8-
"""

total = float(input("Masukkan total belanja: "))

if total > 500000:
    diskon = total * 0.10
else:
    diskon = 0

bayar = total - diskon
print("Total bayar setelah diskon:", bayar)

"""Penjelasan Singkat

- Gunakan if untuk cek apakah belanja > 500.000.

- Kalau iya, beri diskon 10%.

- Kalau tidak, tidak ada diskon.
"""