# -*- coding: utf-8 -*-
"""11UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wq_lZt8zBkEV7AwhPA8EKNY-q5cZVpE2
"""

nilai = []

for i in range(5):
    n = int(input(f"Nilai siswa ke-{i+1}: "))
    nilai.append(n)

tertinggi = max(nilai)
posisi = nilai.index(tertinggi) + 1

print(f"Nilai tertinggi: {tertinggi}, siswa ke-{posisi}")

"""Studi Kasus 1:

Faktorial dengan Rekursi

Manfaat Penggunaan Fungsi:

Modularisasi: Membuat kode lebih terstruktur dan mudah dibaca.

Reusabilitas: Fungsi bisa digunakan berkali-kali tanpa menulis ulang kode.

Debugging lebih mudah karena bisa mengisolasi masalah dalam satu fungsi.

Penjelasan Rekursi: Rekursi adalah teknik pemrograman di mana suatu fungsi memanggil dirinya sendiri untuk menyelesaikan masalah yang lebih kecil
"""