# -*- coding: utf-8 -*-
"""12UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZTh7Y_1UIbJE53dgL5Bed0MRt4Pw528
"""

nilai = []

for i in range(5):
    n = int(input(f"Nilai siswa ke-{i+1}: "))
    nilai.append(n)

tertinggi = max(nilai)
posisi = nilai.index(tertinggi) + 1

print(f"Nilai tertinggi: {tertinggi}, siswa ke-{posisi}")

"""Penjelasan Singkat

- Perulangan dipakai supaya input nilai bisa dilakukan 5 kali tanpa nulis kode berulang.

- List untuk menyimpan semua nilai siswa.

- Cari nilai tertinggi dengan fungsi max() dan cari posisi siswa dengan index().
"""