# -*- coding: utf-8 -*-
"""14UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvJPBvglAT6-ajLbu9kbWAzPY3mCrHPm
"""

total = 0

for i in range(3):
    harga = float(input(f"Harga barang ke-{i+1}: Rp"))
    total += harga

print(f"Total: Rp{total:.2f}")

"""Penjelasan Algoritma:

Langkah-langkah:

1. Inisialisasi total ke 0.

2. Lakukan perulangan sebanyak 3 kali untuk:

 - Meminta pengguna memasukkan harga satu barang.

 - Menambahkan harga barang ke variabel total.

3. Tampilkan total harga setelah semua input selesai.


Keterangan:

1. for i in range(3) → mengulang 3 kali.

2. float(input(...)) → menerima input angka desimal.

3. total += harga → menambahkan harga ke total.

4. :.2f → menampilkan dua angka di belakang koma (format rupiah).
"""