# -*- coding: utf-8 -*-
"""15UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nSLHpxuumlK4hmJCSL2K0dIgvouP4Vs
"""

n1 = float(input("Nilai 1: "))
n2 = float(input("Nilai 2: "))
n3 = float(input("Nilai 3: "))

rata = (n1 + n2 + n3) / 3

if rata >= 75:
    print("LULUS")
else:
    print("TIDAK LULUS")

""" Studi Kasus:

 Cek Kelulusan

Tujuan:
Cek apakah siswa lulus berdasarkan rata-rata 3 nilai.


Penjelasan Singkat:
- Tipe data float: Menyimpan nilai desimal.

- Operator +, /, >=: Digunakan untuk hitung rata-rata dan cek apakah ≥ 75.

- if-else: Menentukan status lulus atau tidak.
"""